# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# include <agpack/preprocessor/config/config.hpp>
#
# if AGPACK_PP_CONFIG_FLAGS() & AGPACK_PP_CONFIG_DMC()
#     include <agpack/preprocessor/detail/dmc/auto_rec.hpp>
# else
#
# ifndef AGPACK_PREPROCESSOR_DETAIL_AUTO_REC_HPP
# define AGPACK_PREPROCESSOR_DETAIL_AUTO_REC_HPP
#
# include <agpack/preprocessor/control/iif.hpp>
#
# /* AGPACK_PP_AUTO_REC */
#
# define AGPACK_PP_AUTO_REC(pred, n) AGPACK_PP_NODE_ENTRY_ ## n(pred)
#
# define AGPACK_PP_NODE_ENTRY_256(p) AGPACK_PP_NODE_128(p)(p)(p)(p)(p)(p)(p)(p)
# define AGPACK_PP_NODE_ENTRY_128(p) AGPACK_PP_NODE_64(p)(p)(p)(p)(p)(p)(p)
# define AGPACK_PP_NODE_ENTRY_64(p) AGPACK_PP_NODE_32(p)(p)(p)(p)(p)(p)
# define AGPACK_PP_NODE_ENTRY_32(p) AGPACK_PP_NODE_16(p)(p)(p)(p)(p)
# define AGPACK_PP_NODE_ENTRY_16(p) AGPACK_PP_NODE_8(p)(p)(p)(p)
# define AGPACK_PP_NODE_ENTRY_8(p) AGPACK_PP_NODE_4(p)(p)(p)
# define AGPACK_PP_NODE_ENTRY_4(p) AGPACK_PP_NODE_2(p)(p)
# define AGPACK_PP_NODE_ENTRY_2(p) AGPACK_PP_NODE_1(p)
#
# define AGPACK_PP_NODE_128(p) AGPACK_PP_IIF(p(128), AGPACK_PP_NODE_64, AGPACK_PP_NODE_192)
#    define AGPACK_PP_NODE_64(p) AGPACK_PP_IIF(p(64), AGPACK_PP_NODE_32, AGPACK_PP_NODE_96)
#        define AGPACK_PP_NODE_32(p) AGPACK_PP_IIF(p(32), AGPACK_PP_NODE_16, AGPACK_PP_NODE_48)
#            define AGPACK_PP_NODE_16(p) AGPACK_PP_IIF(p(16), AGPACK_PP_NODE_8, AGPACK_PP_NODE_24)
#                define AGPACK_PP_NODE_8(p) AGPACK_PP_IIF(p(8), AGPACK_PP_NODE_4, AGPACK_PP_NODE_12)
#                    define AGPACK_PP_NODE_4(p) AGPACK_PP_IIF(p(4), AGPACK_PP_NODE_2, AGPACK_PP_NODE_6)
#                        define AGPACK_PP_NODE_2(p) AGPACK_PP_IIF(p(2), AGPACK_PP_NODE_1, AGPACK_PP_NODE_3)
#                            define AGPACK_PP_NODE_1(p) AGPACK_PP_IIF(p(1), 1, 2)
#                            define AGPACK_PP_NODE_3(p) AGPACK_PP_IIF(p(3), 3, 4)
#                        define AGPACK_PP_NODE_6(p) AGPACK_PP_IIF(p(6), AGPACK_PP_NODE_5, AGPACK_PP_NODE_7)
#                            define AGPACK_PP_NODE_5(p) AGPACK_PP_IIF(p(5), 5, 6)
#                            define AGPACK_PP_NODE_7(p) AGPACK_PP_IIF(p(7), 7, 8)
#                    define AGPACK_PP_NODE_12(p) AGPACK_PP_IIF(p(12), AGPACK_PP_NODE_10, AGPACK_PP_NODE_14)
#                        define AGPACK_PP_NODE_10(p) AGPACK_PP_IIF(p(10), AGPACK_PP_NODE_9, AGPACK_PP_NODE_11)
#                            define AGPACK_PP_NODE_9(p) AGPACK_PP_IIF(p(9), 9, 10)
#                            define AGPACK_PP_NODE_11(p) AGPACK_PP_IIF(p(11), 11, 12)
#                        define AGPACK_PP_NODE_14(p) AGPACK_PP_IIF(p(14), AGPACK_PP_NODE_13, AGPACK_PP_NODE_15)
#                            define AGPACK_PP_NODE_13(p) AGPACK_PP_IIF(p(13), 13, 14)
#                            define AGPACK_PP_NODE_15(p) AGPACK_PP_IIF(p(15), 15, 16)
#                define AGPACK_PP_NODE_24(p) AGPACK_PP_IIF(p(24), AGPACK_PP_NODE_20, AGPACK_PP_NODE_28)
#                    define AGPACK_PP_NODE_20(p) AGPACK_PP_IIF(p(20), AGPACK_PP_NODE_18, AGPACK_PP_NODE_22)
#                        define AGPACK_PP_NODE_18(p) AGPACK_PP_IIF(p(18), AGPACK_PP_NODE_17, AGPACK_PP_NODE_19)
#                            define AGPACK_PP_NODE_17(p) AGPACK_PP_IIF(p(17), 17, 18)
#                            define AGPACK_PP_NODE_19(p) AGPACK_PP_IIF(p(19), 19, 20)
#                        define AGPACK_PP_NODE_22(p) AGPACK_PP_IIF(p(22), AGPACK_PP_NODE_21, AGPACK_PP_NODE_23)
#                            define AGPACK_PP_NODE_21(p) AGPACK_PP_IIF(p(21), 21, 22)
#                            define AGPACK_PP_NODE_23(p) AGPACK_PP_IIF(p(23), 23, 24)
#                    define AGPACK_PP_NODE_28(p) AGPACK_PP_IIF(p(28), AGPACK_PP_NODE_26, AGPACK_PP_NODE_30)
#                        define AGPACK_PP_NODE_26(p) AGPACK_PP_IIF(p(26), AGPACK_PP_NODE_25, AGPACK_PP_NODE_27)
#                            define AGPACK_PP_NODE_25(p) AGPACK_PP_IIF(p(25), 25, 26)
#                            define AGPACK_PP_NODE_27(p) AGPACK_PP_IIF(p(27), 27, 28)
#                        define AGPACK_PP_NODE_30(p) AGPACK_PP_IIF(p(30), AGPACK_PP_NODE_29, AGPACK_PP_NODE_31)
#                            define AGPACK_PP_NODE_29(p) AGPACK_PP_IIF(p(29), 29, 30)
#                            define AGPACK_PP_NODE_31(p) AGPACK_PP_IIF(p(31), 31, 32)
#            define AGPACK_PP_NODE_48(p) AGPACK_PP_IIF(p(48), AGPACK_PP_NODE_40, AGPACK_PP_NODE_56)
#                define AGPACK_PP_NODE_40(p) AGPACK_PP_IIF(p(40), AGPACK_PP_NODE_36, AGPACK_PP_NODE_44)
#                    define AGPACK_PP_NODE_36(p) AGPACK_PP_IIF(p(36), AGPACK_PP_NODE_34, AGPACK_PP_NODE_38)
#                        define AGPACK_PP_NODE_34(p) AGPACK_PP_IIF(p(34), AGPACK_PP_NODE_33, AGPACK_PP_NODE_35)
#                            define AGPACK_PP_NODE_33(p) AGPACK_PP_IIF(p(33), 33, 34)
#                            define AGPACK_PP_NODE_35(p) AGPACK_PP_IIF(p(35), 35, 36)
#                        define AGPACK_PP_NODE_38(p) AGPACK_PP_IIF(p(38), AGPACK_PP_NODE_37, AGPACK_PP_NODE_39)
#                            define AGPACK_PP_NODE_37(p) AGPACK_PP_IIF(p(37), 37, 38)
#                            define AGPACK_PP_NODE_39(p) AGPACK_PP_IIF(p(39), 39, 40)
#                    define AGPACK_PP_NODE_44(p) AGPACK_PP_IIF(p(44), AGPACK_PP_NODE_42, AGPACK_PP_NODE_46)
#                        define AGPACK_PP_NODE_42(p) AGPACK_PP_IIF(p(42), AGPACK_PP_NODE_41, AGPACK_PP_NODE_43)
#                            define AGPACK_PP_NODE_41(p) AGPACK_PP_IIF(p(41), 41, 42)
#                            define AGPACK_PP_NODE_43(p) AGPACK_PP_IIF(p(43), 43, 44)
#                        define AGPACK_PP_NODE_46(p) AGPACK_PP_IIF(p(46), AGPACK_PP_NODE_45, AGPACK_PP_NODE_47)
#                            define AGPACK_PP_NODE_45(p) AGPACK_PP_IIF(p(45), 45, 46)
#                            define AGPACK_PP_NODE_47(p) AGPACK_PP_IIF(p(47), 47, 48)
#                define AGPACK_PP_NODE_56(p) AGPACK_PP_IIF(p(56), AGPACK_PP_NODE_52, AGPACK_PP_NODE_60)
#                    define AGPACK_PP_NODE_52(p) AGPACK_PP_IIF(p(52), AGPACK_PP_NODE_50, AGPACK_PP_NODE_54)
#                        define AGPACK_PP_NODE_50(p) AGPACK_PP_IIF(p(50), AGPACK_PP_NODE_49, AGPACK_PP_NODE_51)
#                            define AGPACK_PP_NODE_49(p) AGPACK_PP_IIF(p(49), 49, 50)
#                            define AGPACK_PP_NODE_51(p) AGPACK_PP_IIF(p(51), 51, 52)
#                        define AGPACK_PP_NODE_54(p) AGPACK_PP_IIF(p(54), AGPACK_PP_NODE_53, AGPACK_PP_NODE_55)
#                            define AGPACK_PP_NODE_53(p) AGPACK_PP_IIF(p(53), 53, 54)
#                            define AGPACK_PP_NODE_55(p) AGPACK_PP_IIF(p(55), 55, 56)
#                    define AGPACK_PP_NODE_60(p) AGPACK_PP_IIF(p(60), AGPACK_PP_NODE_58, AGPACK_PP_NODE_62)
#                        define AGPACK_PP_NODE_58(p) AGPACK_PP_IIF(p(58), AGPACK_PP_NODE_57, AGPACK_PP_NODE_59)
#                            define AGPACK_PP_NODE_57(p) AGPACK_PP_IIF(p(57), 57, 58)
#                            define AGPACK_PP_NODE_59(p) AGPACK_PP_IIF(p(59), 59, 60)
#                        define AGPACK_PP_NODE_62(p) AGPACK_PP_IIF(p(62), AGPACK_PP_NODE_61, AGPACK_PP_NODE_63)
#                            define AGPACK_PP_NODE_61(p) AGPACK_PP_IIF(p(61), 61, 62)
#                            define AGPACK_PP_NODE_63(p) AGPACK_PP_IIF(p(63), 63, 64)
#        define AGPACK_PP_NODE_96(p) AGPACK_PP_IIF(p(96), AGPACK_PP_NODE_80, AGPACK_PP_NODE_112)
#            define AGPACK_PP_NODE_80(p) AGPACK_PP_IIF(p(80), AGPACK_PP_NODE_72, AGPACK_PP_NODE_88)
#                define AGPACK_PP_NODE_72(p) AGPACK_PP_IIF(p(72), AGPACK_PP_NODE_68, AGPACK_PP_NODE_76)
#                    define AGPACK_PP_NODE_68(p) AGPACK_PP_IIF(p(68), AGPACK_PP_NODE_66, AGPACK_PP_NODE_70)
#                        define AGPACK_PP_NODE_66(p) AGPACK_PP_IIF(p(66), AGPACK_PP_NODE_65, AGPACK_PP_NODE_67)
#                            define AGPACK_PP_NODE_65(p) AGPACK_PP_IIF(p(65), 65, 66)
#                            define AGPACK_PP_NODE_67(p) AGPACK_PP_IIF(p(67), 67, 68)
#                        define AGPACK_PP_NODE_70(p) AGPACK_PP_IIF(p(70), AGPACK_PP_NODE_69, AGPACK_PP_NODE_71)
#                            define AGPACK_PP_NODE_69(p) AGPACK_PP_IIF(p(69), 69, 70)
#                            define AGPACK_PP_NODE_71(p) AGPACK_PP_IIF(p(71), 71, 72)
#                    define AGPACK_PP_NODE_76(p) AGPACK_PP_IIF(p(76), AGPACK_PP_NODE_74, AGPACK_PP_NODE_78)
#                        define AGPACK_PP_NODE_74(p) AGPACK_PP_IIF(p(74), AGPACK_PP_NODE_73, AGPACK_PP_NODE_75)
#                            define AGPACK_PP_NODE_73(p) AGPACK_PP_IIF(p(73), 73, 74)
#                            define AGPACK_PP_NODE_75(p) AGPACK_PP_IIF(p(75), 75, 76)
#                        define AGPACK_PP_NODE_78(p) AGPACK_PP_IIF(p(78), AGPACK_PP_NODE_77, AGPACK_PP_NODE_79)
#                            define AGPACK_PP_NODE_77(p) AGPACK_PP_IIF(p(77), 77, 78)
#                            define AGPACK_PP_NODE_79(p) AGPACK_PP_IIF(p(79), 79, 80)
#                define AGPACK_PP_NODE_88(p) AGPACK_PP_IIF(p(88), AGPACK_PP_NODE_84, AGPACK_PP_NODE_92)
#                    define AGPACK_PP_NODE_84(p) AGPACK_PP_IIF(p(84), AGPACK_PP_NODE_82, AGPACK_PP_NODE_86)
#                        define AGPACK_PP_NODE_82(p) AGPACK_PP_IIF(p(82), AGPACK_PP_NODE_81, AGPACK_PP_NODE_83)
#                            define AGPACK_PP_NODE_81(p) AGPACK_PP_IIF(p(81), 81, 82)
#                            define AGPACK_PP_NODE_83(p) AGPACK_PP_IIF(p(83), 83, 84)
#                        define AGPACK_PP_NODE_86(p) AGPACK_PP_IIF(p(86), AGPACK_PP_NODE_85, AGPACK_PP_NODE_87)
#                            define AGPACK_PP_NODE_85(p) AGPACK_PP_IIF(p(85), 85, 86)
#                            define AGPACK_PP_NODE_87(p) AGPACK_PP_IIF(p(87), 87, 88)
#                    define AGPACK_PP_NODE_92(p) AGPACK_PP_IIF(p(92), AGPACK_PP_NODE_90, AGPACK_PP_NODE_94)
#                        define AGPACK_PP_NODE_90(p) AGPACK_PP_IIF(p(90), AGPACK_PP_NODE_89, AGPACK_PP_NODE_91)
#                            define AGPACK_PP_NODE_89(p) AGPACK_PP_IIF(p(89), 89, 90)
#                            define AGPACK_PP_NODE_91(p) AGPACK_PP_IIF(p(91), 91, 92)
#                        define AGPACK_PP_NODE_94(p) AGPACK_PP_IIF(p(94), AGPACK_PP_NODE_93, AGPACK_PP_NODE_95)
#                            define AGPACK_PP_NODE_93(p) AGPACK_PP_IIF(p(93), 93, 94)
#                            define AGPACK_PP_NODE_95(p) AGPACK_PP_IIF(p(95), 95, 96)
#            define AGPACK_PP_NODE_112(p) AGPACK_PP_IIF(p(112), AGPACK_PP_NODE_104, AGPACK_PP_NODE_120)
#                define AGPACK_PP_NODE_104(p) AGPACK_PP_IIF(p(104), AGPACK_PP_NODE_100, AGPACK_PP_NODE_108)
#                    define AGPACK_PP_NODE_100(p) AGPACK_PP_IIF(p(100), AGPACK_PP_NODE_98, AGPACK_PP_NODE_102)
#                        define AGPACK_PP_NODE_98(p) AGPACK_PP_IIF(p(98), AGPACK_PP_NODE_97, AGPACK_PP_NODE_99)
#                            define AGPACK_PP_NODE_97(p) AGPACK_PP_IIF(p(97), 97, 98)
#                            define AGPACK_PP_NODE_99(p) AGPACK_PP_IIF(p(99), 99, 100)
#                        define AGPACK_PP_NODE_102(p) AGPACK_PP_IIF(p(102), AGPACK_PP_NODE_101, AGPACK_PP_NODE_103)
#                            define AGPACK_PP_NODE_101(p) AGPACK_PP_IIF(p(101), 101, 102)
#                            define AGPACK_PP_NODE_103(p) AGPACK_PP_IIF(p(103), 103, 104)
#                    define AGPACK_PP_NODE_108(p) AGPACK_PP_IIF(p(108), AGPACK_PP_NODE_106, AGPACK_PP_NODE_110)
#                        define AGPACK_PP_NODE_106(p) AGPACK_PP_IIF(p(106), AGPACK_PP_NODE_105, AGPACK_PP_NODE_107)
#                            define AGPACK_PP_NODE_105(p) AGPACK_PP_IIF(p(105), 105, 106)
#                            define AGPACK_PP_NODE_107(p) AGPACK_PP_IIF(p(107), 107, 108)
#                        define AGPACK_PP_NODE_110(p) AGPACK_PP_IIF(p(110), AGPACK_PP_NODE_109, AGPACK_PP_NODE_111)
#                            define AGPACK_PP_NODE_109(p) AGPACK_PP_IIF(p(109), 109, 110)
#                            define AGPACK_PP_NODE_111(p) AGPACK_PP_IIF(p(111), 111, 112)
#                define AGPACK_PP_NODE_120(p) AGPACK_PP_IIF(p(120), AGPACK_PP_NODE_116, AGPACK_PP_NODE_124)
#                    define AGPACK_PP_NODE_116(p) AGPACK_PP_IIF(p(116), AGPACK_PP_NODE_114, AGPACK_PP_NODE_118)
#                        define AGPACK_PP_NODE_114(p) AGPACK_PP_IIF(p(114), AGPACK_PP_NODE_113, AGPACK_PP_NODE_115)
#                            define AGPACK_PP_NODE_113(p) AGPACK_PP_IIF(p(113), 113, 114)
#                            define AGPACK_PP_NODE_115(p) AGPACK_PP_IIF(p(115), 115, 116)
#                        define AGPACK_PP_NODE_118(p) AGPACK_PP_IIF(p(118), AGPACK_PP_NODE_117, AGPACK_PP_NODE_119)
#                            define AGPACK_PP_NODE_117(p) AGPACK_PP_IIF(p(117), 117, 118)
#                            define AGPACK_PP_NODE_119(p) AGPACK_PP_IIF(p(119), 119, 120)
#                    define AGPACK_PP_NODE_124(p) AGPACK_PP_IIF(p(124), AGPACK_PP_NODE_122, AGPACK_PP_NODE_126)
#                        define AGPACK_PP_NODE_122(p) AGPACK_PP_IIF(p(122), AGPACK_PP_NODE_121, AGPACK_PP_NODE_123)
#                            define AGPACK_PP_NODE_121(p) AGPACK_PP_IIF(p(121), 121, 122)
#                            define AGPACK_PP_NODE_123(p) AGPACK_PP_IIF(p(123), 123, 124)
#                        define AGPACK_PP_NODE_126(p) AGPACK_PP_IIF(p(126), AGPACK_PP_NODE_125, AGPACK_PP_NODE_127)
#                            define AGPACK_PP_NODE_125(p) AGPACK_PP_IIF(p(125), 125, 126)
#                            define AGPACK_PP_NODE_127(p) AGPACK_PP_IIF(p(127), 127, 128)
#    define AGPACK_PP_NODE_192(p) AGPACK_PP_IIF(p(192), AGPACK_PP_NODE_160, AGPACK_PP_NODE_224)
#        define AGPACK_PP_NODE_160(p) AGPACK_PP_IIF(p(160), AGPACK_PP_NODE_144, AGPACK_PP_NODE_176)
#            define AGPACK_PP_NODE_144(p) AGPACK_PP_IIF(p(144), AGPACK_PP_NODE_136, AGPACK_PP_NODE_152)
#                define AGPACK_PP_NODE_136(p) AGPACK_PP_IIF(p(136), AGPACK_PP_NODE_132, AGPACK_PP_NODE_140)
#                    define AGPACK_PP_NODE_132(p) AGPACK_PP_IIF(p(132), AGPACK_PP_NODE_130, AGPACK_PP_NODE_134)
#                        define AGPACK_PP_NODE_130(p) AGPACK_PP_IIF(p(130), AGPACK_PP_NODE_129, AGPACK_PP_NODE_131)
#                            define AGPACK_PP_NODE_129(p) AGPACK_PP_IIF(p(129), 129, 130)
#                            define AGPACK_PP_NODE_131(p) AGPACK_PP_IIF(p(131), 131, 132)
#                        define AGPACK_PP_NODE_134(p) AGPACK_PP_IIF(p(134), AGPACK_PP_NODE_133, AGPACK_PP_NODE_135)
#                            define AGPACK_PP_NODE_133(p) AGPACK_PP_IIF(p(133), 133, 134)
#                            define AGPACK_PP_NODE_135(p) AGPACK_PP_IIF(p(135), 135, 136)
#                    define AGPACK_PP_NODE_140(p) AGPACK_PP_IIF(p(140), AGPACK_PP_NODE_138, AGPACK_PP_NODE_142)
#                        define AGPACK_PP_NODE_138(p) AGPACK_PP_IIF(p(138), AGPACK_PP_NODE_137, AGPACK_PP_NODE_139)
#                            define AGPACK_PP_NODE_137(p) AGPACK_PP_IIF(p(137), 137, 138)
#                            define AGPACK_PP_NODE_139(p) AGPACK_PP_IIF(p(139), 139, 140)
#                        define AGPACK_PP_NODE_142(p) AGPACK_PP_IIF(p(142), AGPACK_PP_NODE_141, AGPACK_PP_NODE_143)
#                            define AGPACK_PP_NODE_141(p) AGPACK_PP_IIF(p(141), 141, 142)
#                            define AGPACK_PP_NODE_143(p) AGPACK_PP_IIF(p(143), 143, 144)
#                define AGPACK_PP_NODE_152(p) AGPACK_PP_IIF(p(152), AGPACK_PP_NODE_148, AGPACK_PP_NODE_156)
#                    define AGPACK_PP_NODE_148(p) AGPACK_PP_IIF(p(148), AGPACK_PP_NODE_146, AGPACK_PP_NODE_150)
#                        define AGPACK_PP_NODE_146(p) AGPACK_PP_IIF(p(146), AGPACK_PP_NODE_145, AGPACK_PP_NODE_147)
#                            define AGPACK_PP_NODE_145(p) AGPACK_PP_IIF(p(145), 145, 146)
#                            define AGPACK_PP_NODE_147(p) AGPACK_PP_IIF(p(147), 147, 148)
#                        define AGPACK_PP_NODE_150(p) AGPACK_PP_IIF(p(150), AGPACK_PP_NODE_149, AGPACK_PP_NODE_151)
#                            define AGPACK_PP_NODE_149(p) AGPACK_PP_IIF(p(149), 149, 150)
#                            define AGPACK_PP_NODE_151(p) AGPACK_PP_IIF(p(151), 151, 152)
#                    define AGPACK_PP_NODE_156(p) AGPACK_PP_IIF(p(156), AGPACK_PP_NODE_154, AGPACK_PP_NODE_158)
#                        define AGPACK_PP_NODE_154(p) AGPACK_PP_IIF(p(154), AGPACK_PP_NODE_153, AGPACK_PP_NODE_155)
#                            define AGPACK_PP_NODE_153(p) AGPACK_PP_IIF(p(153), 153, 154)
#                            define AGPACK_PP_NODE_155(p) AGPACK_PP_IIF(p(155), 155, 156)
#                        define AGPACK_PP_NODE_158(p) AGPACK_PP_IIF(p(158), AGPACK_PP_NODE_157, AGPACK_PP_NODE_159)
#                            define AGPACK_PP_NODE_157(p) AGPACK_PP_IIF(p(157), 157, 158)
#                            define AGPACK_PP_NODE_159(p) AGPACK_PP_IIF(p(159), 159, 160)
#            define AGPACK_PP_NODE_176(p) AGPACK_PP_IIF(p(176), AGPACK_PP_NODE_168, AGPACK_PP_NODE_184)
#                define AGPACK_PP_NODE_168(p) AGPACK_PP_IIF(p(168), AGPACK_PP_NODE_164, AGPACK_PP_NODE_172)
#                    define AGPACK_PP_NODE_164(p) AGPACK_PP_IIF(p(164), AGPACK_PP_NODE_162, AGPACK_PP_NODE_166)
#                        define AGPACK_PP_NODE_162(p) AGPACK_PP_IIF(p(162), AGPACK_PP_NODE_161, AGPACK_PP_NODE_163)
#                            define AGPACK_PP_NODE_161(p) AGPACK_PP_IIF(p(161), 161, 162)
#                            define AGPACK_PP_NODE_163(p) AGPACK_PP_IIF(p(163), 163, 164)
#                        define AGPACK_PP_NODE_166(p) AGPACK_PP_IIF(p(166), AGPACK_PP_NODE_165, AGPACK_PP_NODE_167)
#                            define AGPACK_PP_NODE_165(p) AGPACK_PP_IIF(p(165), 165, 166)
#                            define AGPACK_PP_NODE_167(p) AGPACK_PP_IIF(p(167), 167, 168)
#                    define AGPACK_PP_NODE_172(p) AGPACK_PP_IIF(p(172), AGPACK_PP_NODE_170, AGPACK_PP_NODE_174)
#                        define AGPACK_PP_NODE_170(p) AGPACK_PP_IIF(p(170), AGPACK_PP_NODE_169, AGPACK_PP_NODE_171)
#                            define AGPACK_PP_NODE_169(p) AGPACK_PP_IIF(p(169), 169, 170)
#                            define AGPACK_PP_NODE_171(p) AGPACK_PP_IIF(p(171), 171, 172)
#                        define AGPACK_PP_NODE_174(p) AGPACK_PP_IIF(p(174), AGPACK_PP_NODE_173, AGPACK_PP_NODE_175)
#                            define AGPACK_PP_NODE_173(p) AGPACK_PP_IIF(p(173), 173, 174)
#                            define AGPACK_PP_NODE_175(p) AGPACK_PP_IIF(p(175), 175, 176)
#                define AGPACK_PP_NODE_184(p) AGPACK_PP_IIF(p(184), AGPACK_PP_NODE_180, AGPACK_PP_NODE_188)
#                    define AGPACK_PP_NODE_180(p) AGPACK_PP_IIF(p(180), AGPACK_PP_NODE_178, AGPACK_PP_NODE_182)
#                        define AGPACK_PP_NODE_178(p) AGPACK_PP_IIF(p(178), AGPACK_PP_NODE_177, AGPACK_PP_NODE_179)
#                            define AGPACK_PP_NODE_177(p) AGPACK_PP_IIF(p(177), 177, 178)
#                            define AGPACK_PP_NODE_179(p) AGPACK_PP_IIF(p(179), 179, 180)
#                        define AGPACK_PP_NODE_182(p) AGPACK_PP_IIF(p(182), AGPACK_PP_NODE_181, AGPACK_PP_NODE_183)
#                            define AGPACK_PP_NODE_181(p) AGPACK_PP_IIF(p(181), 181, 182)
#                            define AGPACK_PP_NODE_183(p) AGPACK_PP_IIF(p(183), 183, 184)
#                    define AGPACK_PP_NODE_188(p) AGPACK_PP_IIF(p(188), AGPACK_PP_NODE_186, AGPACK_PP_NODE_190)
#                        define AGPACK_PP_NODE_186(p) AGPACK_PP_IIF(p(186), AGPACK_PP_NODE_185, AGPACK_PP_NODE_187)
#                            define AGPACK_PP_NODE_185(p) AGPACK_PP_IIF(p(185), 185, 186)
#                            define AGPACK_PP_NODE_187(p) AGPACK_PP_IIF(p(187), 187, 188)
#                        define AGPACK_PP_NODE_190(p) AGPACK_PP_IIF(p(190), AGPACK_PP_NODE_189, AGPACK_PP_NODE_191)
#                            define AGPACK_PP_NODE_189(p) AGPACK_PP_IIF(p(189), 189, 190)
#                            define AGPACK_PP_NODE_191(p) AGPACK_PP_IIF(p(191), 191, 192)
#        define AGPACK_PP_NODE_224(p) AGPACK_PP_IIF(p(224), AGPACK_PP_NODE_208, AGPACK_PP_NODE_240)
#            define AGPACK_PP_NODE_208(p) AGPACK_PP_IIF(p(208), AGPACK_PP_NODE_200, AGPACK_PP_NODE_216)
#                define AGPACK_PP_NODE_200(p) AGPACK_PP_IIF(p(200), AGPACK_PP_NODE_196, AGPACK_PP_NODE_204)
#                    define AGPACK_PP_NODE_196(p) AGPACK_PP_IIF(p(196), AGPACK_PP_NODE_194, AGPACK_PP_NODE_198)
#                        define AGPACK_PP_NODE_194(p) AGPACK_PP_IIF(p(194), AGPACK_PP_NODE_193, AGPACK_PP_NODE_195)
#                            define AGPACK_PP_NODE_193(p) AGPACK_PP_IIF(p(193), 193, 194)
#                            define AGPACK_PP_NODE_195(p) AGPACK_PP_IIF(p(195), 195, 196)
#                        define AGPACK_PP_NODE_198(p) AGPACK_PP_IIF(p(198), AGPACK_PP_NODE_197, AGPACK_PP_NODE_199)
#                            define AGPACK_PP_NODE_197(p) AGPACK_PP_IIF(p(197), 197, 198)
#                            define AGPACK_PP_NODE_199(p) AGPACK_PP_IIF(p(199), 199, 200)
#                    define AGPACK_PP_NODE_204(p) AGPACK_PP_IIF(p(204), AGPACK_PP_NODE_202, AGPACK_PP_NODE_206)
#                        define AGPACK_PP_NODE_202(p) AGPACK_PP_IIF(p(202), AGPACK_PP_NODE_201, AGPACK_PP_NODE_203)
#                            define AGPACK_PP_NODE_201(p) AGPACK_PP_IIF(p(201), 201, 202)
#                            define AGPACK_PP_NODE_203(p) AGPACK_PP_IIF(p(203), 203, 204)
#                        define AGPACK_PP_NODE_206(p) AGPACK_PP_IIF(p(206), AGPACK_PP_NODE_205, AGPACK_PP_NODE_207)
#                            define AGPACK_PP_NODE_205(p) AGPACK_PP_IIF(p(205), 205, 206)
#                            define AGPACK_PP_NODE_207(p) AGPACK_PP_IIF(p(207), 207, 208)
#                define AGPACK_PP_NODE_216(p) AGPACK_PP_IIF(p(216), AGPACK_PP_NODE_212, AGPACK_PP_NODE_220)
#                    define AGPACK_PP_NODE_212(p) AGPACK_PP_IIF(p(212), AGPACK_PP_NODE_210, AGPACK_PP_NODE_214)
#                        define AGPACK_PP_NODE_210(p) AGPACK_PP_IIF(p(210), AGPACK_PP_NODE_209, AGPACK_PP_NODE_211)
#                            define AGPACK_PP_NODE_209(p) AGPACK_PP_IIF(p(209), 209, 210)
#                            define AGPACK_PP_NODE_211(p) AGPACK_PP_IIF(p(211), 211, 212)
#                        define AGPACK_PP_NODE_214(p) AGPACK_PP_IIF(p(214), AGPACK_PP_NODE_213, AGPACK_PP_NODE_215)
#                            define AGPACK_PP_NODE_213(p) AGPACK_PP_IIF(p(213), 213, 214)
#                            define AGPACK_PP_NODE_215(p) AGPACK_PP_IIF(p(215), 215, 216)
#                    define AGPACK_PP_NODE_220(p) AGPACK_PP_IIF(p(220), AGPACK_PP_NODE_218, AGPACK_PP_NODE_222)
#                        define AGPACK_PP_NODE_218(p) AGPACK_PP_IIF(p(218), AGPACK_PP_NODE_217, AGPACK_PP_NODE_219)
#                            define AGPACK_PP_NODE_217(p) AGPACK_PP_IIF(p(217), 217, 218)
#                            define AGPACK_PP_NODE_219(p) AGPACK_PP_IIF(p(219), 219, 220)
#                        define AGPACK_PP_NODE_222(p) AGPACK_PP_IIF(p(222), AGPACK_PP_NODE_221, AGPACK_PP_NODE_223)
#                            define AGPACK_PP_NODE_221(p) AGPACK_PP_IIF(p(221), 221, 222)
#                            define AGPACK_PP_NODE_223(p) AGPACK_PP_IIF(p(223), 223, 224)
#            define AGPACK_PP_NODE_240(p) AGPACK_PP_IIF(p(240), AGPACK_PP_NODE_232, AGPACK_PP_NODE_248)
#                define AGPACK_PP_NODE_232(p) AGPACK_PP_IIF(p(232), AGPACK_PP_NODE_228, AGPACK_PP_NODE_236)
#                    define AGPACK_PP_NODE_228(p) AGPACK_PP_IIF(p(228), AGPACK_PP_NODE_226, AGPACK_PP_NODE_230)
#                        define AGPACK_PP_NODE_226(p) AGPACK_PP_IIF(p(226), AGPACK_PP_NODE_225, AGPACK_PP_NODE_227)
#                            define AGPACK_PP_NODE_225(p) AGPACK_PP_IIF(p(225), 225, 226)
#                            define AGPACK_PP_NODE_227(p) AGPACK_PP_IIF(p(227), 227, 228)
#                        define AGPACK_PP_NODE_230(p) AGPACK_PP_IIF(p(230), AGPACK_PP_NODE_229, AGPACK_PP_NODE_231)
#                            define AGPACK_PP_NODE_229(p) AGPACK_PP_IIF(p(229), 229, 230)
#                            define AGPACK_PP_NODE_231(p) AGPACK_PP_IIF(p(231), 231, 232)
#                    define AGPACK_PP_NODE_236(p) AGPACK_PP_IIF(p(236), AGPACK_PP_NODE_234, AGPACK_PP_NODE_238)
#                        define AGPACK_PP_NODE_234(p) AGPACK_PP_IIF(p(234), AGPACK_PP_NODE_233, AGPACK_PP_NODE_235)
#                            define AGPACK_PP_NODE_233(p) AGPACK_PP_IIF(p(233), 233, 234)
#                            define AGPACK_PP_NODE_235(p) AGPACK_PP_IIF(p(235), 235, 236)
#                        define AGPACK_PP_NODE_238(p) AGPACK_PP_IIF(p(238), AGPACK_PP_NODE_237, AGPACK_PP_NODE_239)
#                            define AGPACK_PP_NODE_237(p) AGPACK_PP_IIF(p(237), 237, 238)
#                            define AGPACK_PP_NODE_239(p) AGPACK_PP_IIF(p(239), 239, 240)
#                define AGPACK_PP_NODE_248(p) AGPACK_PP_IIF(p(248), AGPACK_PP_NODE_244, AGPACK_PP_NODE_252)
#                    define AGPACK_PP_NODE_244(p) AGPACK_PP_IIF(p(244), AGPACK_PP_NODE_242, AGPACK_PP_NODE_246)
#                        define AGPACK_PP_NODE_242(p) AGPACK_PP_IIF(p(242), AGPACK_PP_NODE_241, AGPACK_PP_NODE_243)
#                            define AGPACK_PP_NODE_241(p) AGPACK_PP_IIF(p(241), 241, 242)
#                            define AGPACK_PP_NODE_243(p) AGPACK_PP_IIF(p(243), 243, 244)
#                        define AGPACK_PP_NODE_246(p) AGPACK_PP_IIF(p(246), AGPACK_PP_NODE_245, AGPACK_PP_NODE_247)
#                            define AGPACK_PP_NODE_245(p) AGPACK_PP_IIF(p(245), 245, 246)
#                            define AGPACK_PP_NODE_247(p) AGPACK_PP_IIF(p(247), 247, 248)
#                    define AGPACK_PP_NODE_252(p) AGPACK_PP_IIF(p(252), AGPACK_PP_NODE_250, AGPACK_PP_NODE_254)
#                        define AGPACK_PP_NODE_250(p) AGPACK_PP_IIF(p(250), AGPACK_PP_NODE_249, AGPACK_PP_NODE_251)
#                            define AGPACK_PP_NODE_249(p) AGPACK_PP_IIF(p(249), 249, 250)
#                            define AGPACK_PP_NODE_251(p) AGPACK_PP_IIF(p(251), 251, 252)
#                        define AGPACK_PP_NODE_254(p) AGPACK_PP_IIF(p(254), AGPACK_PP_NODE_253, AGPACK_PP_NODE_255)
#                            define AGPACK_PP_NODE_253(p) AGPACK_PP_IIF(p(253), 253, 254)
#                            define AGPACK_PP_NODE_255(p) AGPACK_PP_IIF(p(255), 255, 256)
#
# endif
# endif
